pipeline:
  build:
    image: nextcloudci/php7.2:php7.2-9
    commands:
      #- apt-get -y update || true
      #- apt-get -y install cgroup-bin curl
      #- curl -fsSL -o /tmp/lando-latest.deb http://installer.kalabox.io/lando-latest-dev.deb
      #- apt-get install iptables docker-ce
      #- apt-get install -f
      #- dpkg -i /tmp/lando-latest.deb 
      #- lando version
      #- composer --verbose validate
      #- composer --verbose install
      - ls -l
  slack:
    image: plugins/slack
    channel: drone
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        Oh yeah! build {{build.number}} Good job.
      {{else}}
        Mince! @Ali build {{build.number}} failed. Fix me please.
      {{/success}}    
#services:
#  - image: docker
  


+branches: master
