pipeline:
  build:
    image: plugins/docker
    commands:
      - apt-get -y update || true
      - apt-get -y install cgroup-bin curl
      - curl -fsSL -o /tmp/lando-latest.deb http://installer.kalabox.io/lando-latest-dev.deb
      - apt-get install iptables docker-ce
      - apt-get install -f
      - dpkg -i /tmp/lando-latest.deb 
      - lando version
  slack:
    image: plugins/slack
    channel: dev
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        Oh yeah! build {{build.number}} Good job.
      {{else}}
        Mince! build {{build.number}} failed. Fix me please.
      {{/success}}    
#services:
#  - image: docker
  


+branches: master
