pipeline:
  build:
    image: jpetazzo/dind
    env:
      - CI=drone
    script:
      - wrapdocker && docker images
  slack:
    image: plugins/slack
    channel: drone
    webhook: https://hooks.slack.com/services/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
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        Oh yeah! build {{build.number}} Good job.
      {{else}}
        Mince! @Ali build {{build.number}} failed. Fix me please.
      {{/success}}    
#services:
#  - image: docker
  


+branches: master
